name: jeepney_tracker
description: "Real-time jeepney tracking app for Philippine commuters - SDG 11.2 Sustainable Transport"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  
  provider: ^6.1.1
  go_router: ^14.2.7
  
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  
  intl: ^0.20.2
  
  flutter_svg: ^2.0.10+1
  animate_do: ^3.3.4
  
  dio: ^5.7.0
  logger: ^2.4.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
